### ISSUE TITLE
README.md --  Environment Description

### ISSUE THREAD

**Issue by runck014** [LRosen656/USDA_GEMS_RGB_COVER#3]
The readme overall looks good. There is not a description of the computing environment hosting Jupiter notebooks. I would recommend either using the GEMS agroinformatics platform, where the data can be hosted, or using colab. Colab might be easier since all of the imagery is already hosted there. Either way, specifying this is important.

Additionally, I assume you're managing your environment using conda. Doing a dump of your environment into a requirements.txt file and keeping this on the repo (and then describing setup instructions) will help make it so the next person to work with the code base can be successful.

See here >> https://iqcode.com/code/python/create-requirementstxt-conda

**Comment by LRosen656** [comment]
Would I still be able to store everything on a local hard drive?

**Comment by LRosen656** [comment]
requirements.txt created
