### ISSUE TITLE
USDA_GEMS_RGB_COVER/Rename_Images.ipynb

### ISSUE THREAD

**Issue by pmewing** [LRosen656/USDA_GEMS_RGB_COVER#5]
You're renaming the images as .tif, but the format is still .jpg since you're not re-writing them (just copying them). Probably best to keep the original extension. 

In the image_crop, you do rewrite it as a .tif.

Otherwise, looks great. Super clear code.

**Comment by LRosen656** [comment]
Changed it back to jpegs
